name: Format and Lint

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    format_and_lint:
        name: "Format and lint"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python
                uses: actions/setup-python@v2
            -   name: Install development dependencies
                run: pipx run poetry install --only docs,lint
            -   name: Check code formatting with black
                run: pipx run poetry run black . --check --diff
            -   name: Lint with flake8
                run: |
                    # stop the build if there are Python syntax errors or undefined names
                    pipx run poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    # exit-zero treats all errors as warnings. Default line length of black is 88
                    pipx run poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
            -   name: Build docs
                run: READTHEDOCS=True pipx run poetry run make -C docs html
